platform :ios, '9.0'
use_frameworks!

target 'TemplateSwiftAPP' do
    

    pod 'Alamofire'          # 网络请求 https://github.com/Alamofire/Alamofire，同 AFNetworking
    pod 'SnapKit'            # 布局框架 https://github.com/SnapKit/SnapKit，同 Masonry
    
    pod 'Kingfisher'         # 缓存图片 https://github.com/onevcat/Kingfisher，同 SDWebImage
    pod 'RxSwift'            # 响应式编程框架 https://github.com/ReactiveX/RxSwift
    pod 'SVProgressHUD'      # 提示功能 https://github.com/SVProgressHUD/SVProgressHUD
    pod 'MJRefresh'          # 上拉和下拉刷新框架 https://github.com/CoderMJLee/MJRefresh
    
    pod 'SQLite.swift'       # SQLite https://github.com/stephencelis/SQLite.swift.git
    pod 'IQKeyboardManagerSwift'  # 键盘交互 https://github.com/hackiftekhar/IQKeyboardManager
    
    pod 'SwiftyMarkdown'     # Markdown 渲染 https://github.com/SimonFairbairn/SwiftyMarkdown
    pod 'MarkdownView'       # Markdown 渲染 https://github.com/keitaoouchi/MarkdownView.git
    
    # 友盟分享
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'
    
end
